// The fonts each template sets (from its fontsLink): ads and posts use the same type as the client's site.
// Generated from the templates; sans only (Apereel's rule). Heading first, then body.
export const TEMPLATE_FONTS: Record<string, { heading: string; body: string }> = {
  crown: { heading: "Inter Tight", body: "Inter" },
  studio: { heading: "DM Sans", body: "DM Sans" },
  ledger: { heading: "Archivo", body: "Archivo" },
  apex: { heading: "Barlow Condensed", body: "Barlow" },
  stride: { heading: "Anton", body: "Inter" },
  fleet: { heading: "Figtree", body: "Figtree" },
  maison: { heading: "Jost", body: "Jost" },
  flow: { heading: "Manrope", body: "Manrope" },
  lab: { heading: "Space Grotesk", body: "Inter" },
  regent: { heading: "Outfit", body: "Outfit" },
  torque: { heading: "Sora", body: "Sora" },
  grid: { heading: "Onest", body: "Onest" },
  atelier: { heading: "Figtree", body: "Figtree" },
  heritage: { heading: "Bricolage Grotesque", body: "Inter" },
  arena: { heading: "Saira Condensed", body: "Inter" },
  chrono: { heading: "Chakra Petch", body: "Inter" },
  calm: { heading: "Albert Sans", body: "Albert Sans" },
  depot: { heading: "Nunito Sans", body: "Nunito Sans" },
  officina: { heading: "Red Hat Display", body: "Red Hat Text" },
  sleek: { heading: "Instrument Sans", body: "Instrument Sans" },
  outpost: { heading: "Oswald", body: "Source Sans 3" },
  showroom: { heading: "Mulish", body: "Mulish" },
  edge: { heading: "Exo 2", body: "Inter" },
  flyer: { heading: "Archivo Narrow", body: "Inter" },
  gallery: { heading: "Space Grotesk", body: "IBM Plex Mono" },
  legacy: { heading: "Urbanist", body: "Urbanist" },
  field: { heading: "Barlow Semi Condensed", body: "Barlow" },
  campaign: { heading: "Archivo", body: "Inter" },
  drive: { heading: "Plus Jakarta Sans", body: "Plus Jakarta Sans" },
  pop: { heading: "Nunito", body: "Nunito" },
};
